name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*

pr:
  branches:
    include:
    - master
    - release*
    - feature*

resources:
- repo: self
  clean: true
jobs:
- template: templates/credscan.yml

- job: Linux_CI

  displayName: Markdown and Common Tests

  pool:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture Environment
    condition: succeededOrFailed()

  - powershell: |
      Install-module Pester -Scope CurrentUser -Force -MaximumVersion 4.99
    displayName: Install Pester
    condition: succeededOrFailed()

  - bash: |
      curl -o- --progress-bar -L https://yarnpkg.com/install.sh | bash
    displayName: Bootstrap Yarn
    condition: succeededOrFailed()

  - bash: |
      sudo yarn global add markdown-spellcheck@0.11.0
    displayName: Install mdspell
    condition: succeededOrFailed()

  - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhmmss"))"
    displayName: Set Build Name for Non-PR
    condition: ne(variables['Build.Reason'], 'PullRequest')

  - bash: |
      mdspell '**/*.md' '!**/Pester/**/*.md' --ignore-numbers --ignore-acronyms --report --en-us;
    displayName: Test Spelling in Markdown
    condition: succeededOrFailed()
